title: Henrik's github lab pages
author: Henrik
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is for learning github pages with github labs.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
